# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# for a detailed guide
name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment:
      name: publish
      url: https://pypi.org/project/wagtail-modeladmin
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flit
          python -m flit install --symlink

      - name: Build
        run: python -m flit build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
